### PR TITLE
fix: Js__Int.fromString binding

### LINKED ISSUE #6: Js__Int.fromString generates `string.Number()` instead of `Number(string)`
https://github.com/bloodyowl/rescript-js/blob/4f44c2d9e4e1fd0dce438dd50e1e4fa57d3c3a16/src/Js__Int.res#L19

### PR DESCRIPTION
**Pull request by illusionalsagacity**
fixes #6

### CODE REVIEW

**Comment by bloodyowl** [comment]
Nice catch! Thanks @illusionalsagacity

**Comment by bloodyowl** [comment]
@illusionalsagacity Released in v0.6.0. Added an additional change to make `Int.fromString` safe (returning an `option<int>`) with a little bit of runtime.

**Comment by illusionalsagacity** [comment]
@bloodyowl the `Float.fromString` method would also be subject to that `NaN` issue too, should that be changed to return an `option<float>` too?

**Comment by bloodyowl** [comment]
`NaN` being a legal float, I think of it less of a problem.

**Pull request merged**
